spring.application.name=backend

spring.data.mongodb.uri=mongodb+srv://batuhanbaydar:cs308cs308@cs308team16.bwextae.mongodb.net/cs308_ecommerce?retryWrites=true&w=majority
spring.data.mongodb.database=cs308_ecommerce

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tidl.cs308@gmail.com
spring.mail.password=cajvlncovvffeybw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.default-encoding=UTF-8
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# Chat uploads directory
chat.upload-dir=uploads/chat
app.mail.from=noreply@tidl-store.com
